Add Associations
RIT-Crowd-Comic/crowd-comic-back-end pull request #17
Opened 2024-06-28 15:21 UTC by nca6109

### Associations
Added associations between: 
- User & Panel Set (One-To-Many)
- Panel Set & Panel (One-To-Many)
- Panel Set & Hook (One-To-One)
- Panel & Hook (One-To-Many)

#### Eager loading examples
Associations were tested with eager loading calls. Test runs below

- User & Panel Set
     - User -> Panel Set
        - ![User-PanelSets_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/865dee57-adec-44bc-91ec-d11c36d7e5f2)
        - ![User-PanelSets](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/64dc83ff-e4cf-4148-b4f7-05c2771e9d93)
     - Panel Set -> User
        - ![PanelSet-User_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/cce28618-ff59-40ba-b8f1-32926c037249)
        - ![PanelSet-User](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/1326bf29-6444-41e8-8ac2-a2697df5baec)
   
- Panel Set & Panel
     - Panel Set -> Panel
        - ![PanelSet-Panel_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/c18f2f18-73d3-4bcd-86bb-680890516e5c)
        - ![PanelSet-Panel](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/4da7fad2-8e37-479e-ab8d-c5a52a0a58bb)
     - Panel -> Panel Set
        - ![Panel-PanelSet_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/b8631309-ace9-4b7b-adac-22aa50ef2391)
        - ![Panel-PanelSet](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/5f9f6e8b-5ec8-4637-9cbc-92e7ef7e097f)
     
- Panel Set & Hook
     - Panel Set -> Hook
        - ![PanelSet-Hook_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/8f6a1362-d38f-46b3-9162-bbf02aecd8d0)
        - ![PanelSet-Hook](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/31548902-ffa6-4ad2-9912-c7020f400d45)
     - Hook -> Panel Set
        - ![Hook-PanelSet_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/eb5182de-a773-44e2-9e73-42c6595d36b2)
        - ![Hook-PanelSet](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/424ca9ac-6652-46f9-bfb6-dc60e4740652)
        
- Panel & Hook
     - Panel -> Hook
        - ![Panel-Hook_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/ecbf1da0-f173-4871-9a3f-4bd4c7db40ce)
        - ![Panel-Hook](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/daef7705-48cd-48d5-a928-11806d4f0c3c)
     - Hook -> Panel
        - ![Hook-Panel_Code](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/a7381c31-63b4-40ee-8084-90436897a2f1)
        - ![Hook-Panel](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/70412057/b3f2e1b3-0755-4c59-a447-20d3d3da32e4)

2024-06-28 15:39 UTC, BlckHawker reviewed
Looks good on paper. Can you refactor the controllers that require associations, such as `_createPanelSetController`?

2024-06-28 15:40 UTC, wct9667 approved these changes
Approved!

2024-07-01 15:29 UTC, BlckHawker requested changes
Nice job. Only found one bug

2024-07-01 15:29 UTC, BlckHawker commented on src/services/panelService.ts
> +    const panels = panel_set.panels as IPanel[];
This should probably be changed to return an empty array, and return a 404
![image](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/62062830/36652f83-4a39-4ac6-8196-fb6b4092a18b)

2024-07-01 15:54 UTC, nca6109 commented on src/services/panelService.ts
> +    const panels = panel_set.panels as IPanel[];
Fixed the issue here and the same one in `getAllPanelSetsFromUser`

2024-07-01 15:58 UTC, BlckHawker approved these changes
![sonic-boom-knuckles](https://github.com/RIT-Crowd-Comic/crowd-comic-back-end/assets/62062830/fa252149-1382-4793-b178-ef3f9764e0ba)

2024-07-01 15:58 UTC, merged