Create query to get hooks from panel set
RIT-Crowd-Comic/crowd-comic-back-end pull request #33
Opened 2024-07-17 19:21 UTC by BlckHawker

Did not add unit test as pressed for time

2024-07-18 21:03 UTC, nca6109 requested changes
Formatting concerns probably can be fixed by just running through the linter

2024-07-18 21:03 UTC, nca6109 commented on src/requestHandlers/hook.ts
> +    const response = await _getAllHooksByPanelSetIdController(sequelize)(Number(id));
Should validate arguments like in other request handlers
```suggestion
    const id = Number(req.params.id);
    const validArgs = assertArgumentsNumber({ id });
    if (!validArgs.success) return res.status(400).json(validArgs);
```

2024-07-18 21:03 UTC, nca6109 commented on src/requestHandlers/image.ts
> +import { sanitizeResponse, assertArgumentsString, assertArgumentsNumber } from './utils';
```suggestion
import { sanitizeResponse, assertArgumentsString, assertArgumentsNumber } from './utils';
```

2024-07-18 21:03 UTC, nca6109 commented on src/requestHandlers/image.ts
> +        return await Promise.all(panels.map(async (panel) => await imageService.getImage(panel.image)));
Could be worth adding a null check on the panels to avoid a failed `getImage` call?

2024-07-18 21:03 UTC, nca6109 commented on src/requestHandlers/image.ts
> +
```suggestion
    return sanitizeResponse(response, res, `A panel set with an id of ${id} does not exist`);
```

2024-07-18 21:03 UTC, nca6109 commented on src/requestHandlers/populate.ts
> +            await _publishController(sequelize)(user.id, panelImages[3], panelImages[4], panelImages[5], hook3, 3) as any,
```suggestion
            await _publishController(sequelize)(user.id, panelImages[0], panelImages[1], panelImages[2], hook1, undefined) as any,
            await _publishController(sequelize)(user.id, panelImages[3], panelImages[4], panelImages[5], hook2, 1) as any,
            await _publishController(sequelize)(user.id, panelImages[3], panelImages[4], panelImages[5], hook3, 3) as any,
```

2024-07-19 03:42 UTC, BlckHawker commented on src/requestHandlers/image.ts
> +        return await Promise.all(panels.map(async (panel) => await imageService.getImage(panel.image)));
It will never be null as it's an array. If `panels` empty, then it will just return an empty array

2024-07-19 03:43 UTC, BlckHawker commented on src/requestHandlers/image.ts
> +import { sanitizeResponse, assertArgumentsString, assertArgumentsNumber } from './utils';
I don't see the difference between these two lines

2024-07-19 03:43 UTC, BlckHawker commented on src/requestHandlers/image.ts
> +
I don't see the difference between these two lines

2024-07-19 14:08 UTC, nca6109 approved these changes

2024-07-19 15:25 UTC, merged